eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  endpoints:
   web:
    exposure:
      include : '*'
      
  tracing:
    sampling:
      probability: 1.0
